networks:
  default:
    name: cf.net
    driver: bridge
      

services:
  db:
    container_name: cf_db
    hostname: pg.cf.net
    build: 
      context: .
      dockerfile: ./postgres.Dockerfile
    ports: 
    - "5432:5432"
    environment: 
      POSTGRES_PASSWORD: blarg123!
      TZ: Canada/Eastern 

  py:
    container_name: cf_py
    build:
      context: .
      dockerfile: ./python.Dockerfile
    depends_on:
      - cf_db
    volumes: 
    - "../:/cartoforum"
  
  geos:
    container_name: cf_geos
    hostname: geos.cf.net
    build:
      context: .
      dockerfile: ./geos.Dockerfile
    ports:
    - "8080:8080" 
    environment:
      GEOSERVER_HOME: /usr/share/geoserver
    volumes: 
    - "data_dir:/usr/share/geoserver"    
